name: 'Lint Action'
description: 'Lint the Code'
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with flake8
#      shell: bash
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with pylint
      shell: bash
      run: |
        # lint the module, and the tests
        pylint --rcfile=.pylintrc bin flask_site
