name: 'Lint Action'
description: 'Lint the Great Football Pool'
inputs:
  settings_json:
    description: "Text blob containing the json for the settings"
    required: false
    default: '{"hello world": 1}'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        echo "Before CD"
        pwd
        echo ${{ github.workspace }}
        cd ${{ github.workspace }}
        echo "After CD"
        pwd
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Test Inputs
      run: echo ${{ inputs.settings_json }}
      shell: bash
    - name: Test for echo
      run: echo "Github Workspace ${{ github.workspace }}"
      shell: bash
    - name: Install config file
      run: |
        cat << EOF > ${{ github.workspace }}/conf/settings.json
        ${{ inputs.settings_json }}
        EOF
      shell: bash
    - name: Copy *.pth into site packages
      run: |
        cp ${{ github.workspace }}/conf/tgfp_paths.pth env/lib/python3.*/site-packages
      shell: bash
    - name: Lint with pylint
      run: |
        env/bin/python -m pylint --rcfile .pylintrc bin/*.py bin/discord/*.py bin/healthchecks/*.py flask_site/include/*.py
      shell: bash
    - name: Check code with flake8
      run: |
        env/bin/python -m flake8 --config .flake8 bin/*.py bin/discord/*.py bin/healthchecks/*.py flask_site/include/*.py
      shell: bash
