name: 'Lint Action'
description: 'Lint the Code'
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      shell: bash
      run: |
        # lint the module, and the tests
        pylint --rcfile=.pylintrc bin flask_site
