name: Get Prod / Dev settings.json

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Fetch settings from secrets
    runs-on: macos-11.0
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create Production settings.json file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        password: ${{ secrets.DEV_SERVER_PASSWORD }}
        script: |
          cat << EOF > ${{ secrets.DEV_SERVER_HOME }}/conf/dev.settings.json
          ${{ secrets.DEV_SERVER_SETTINGS_JSON }}
          EOF

    - name: Create Prod Bot private key file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        password: ${{ secrets.DEV_SERVER_PASSWORD }}
        script: |
          cat << EOF > ${{ secrets.DEV_SERVER_HOME }}/conf/prod_bot_private.key
          ${{ secrets.PROD_BOT_SERVER_PRIVATE_KEY }}
          EOF

    - name: Create Prod Web private key file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        password: ${{ secrets.DEV_SERVER_PASSWORD }}
        script: |
          cat << EOF > ${{ secrets.DEV_SERVER_HOME }}/conf/prod_web_private.key
          ${{ secrets.PROD_WEB_SERVER_PRIVATE_KEY }}
          EOF

    - name: Create Dev settings.json file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        password: ${{ secrets.DEV_SERVER_PASSWORD }}
        script: |
          cat << EOF > ${{ secrets.DEV_SERVER_HOME }}/conf/prod.settings.json
          ${{ secrets.PROD_SERVER_SETTINGS_JSON }}
          EOF
