name: Lint Only

on: [pull_request]

jobs:
  build:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pylint --rcfile .pylintrc bin/*.py flask_site/include/*.py
    - name: Check code with flake8
      run: |
        flake8 --config .flake8 bin/*.py flask_site/include/*.py
    - name: ShellCheck
      run: |
        shellcheck -x bin/*.sh
        shellcheck -x flask_site/run.sh
    - name: Unit Tests
      run: |
        python -m pytest --ignore=tests/test_mongo_backup.py