name: Lint Only

on: [pull_request]

jobs:
  build:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install config file
      run: |
        cat << EOF > ${{ github.workspace }}/conf/settings.json
        ${{ secrets.PROD_SERVER_SETTINGS_JSON }}
        EOF
    - name: Lint with pylint
      run: |
        env/bin/python -m pylint --rcfile .pylintrc bin/*.py flask_site/include/*.py
    - name: Check code with flake8
      run: |
        env/bin/python -m flake8 --config .flake8 bin/*.py flask_site/include/*.py
    - name: Unit Tests
      run: |
        env/bin/python -m pytest --ignore=tests/test_mongo_backup.py
      env:
        PYTHONPATH: ${{ github.workspace }}/bin:${{ github.workspace }}/bin/discord:${{ github.workspace }}/bin/healthchecks

