name: Lint Only

on:
  workflow_dispatch:

jobs:
  build:
    name: Lint Check
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install config file
      run: |
        cat << EOF > ${{ github.workspace }}/conf/settings.json
        ${{ secrets.PROD_SERVER_SETTINGS_JSON }}
        EOF

    - name: Copy *.pth into site packages
      run: |
        cp ${{ github.workspace }}/conf/tgfp_paths.pth env/lib/python3.*/site-packages
    - name: Lint with pylint
      run: |
        env/bin/python -m pylint --rcfile .pylintrc bin/*.py flask_site/include/*.py
    - name: Check code with flake8
      run: |
        env/bin/python -m flake8 --config .flake8 bin/*.py flask_site/include/*.py
