name: Lint Only

on: [pull_request]

jobs:
  build:
    name: Included Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run my own lint action
        uses: ./.github/actions/lint
